### PR TITLE
Points Reference 2.0.2 Changes

### PR DESCRIPTION
**Pull request by Harleqyin**
Changed points values, changes to Low Profile and fixed error with Dooku's Makashi Mastery not showing in datasheet.
Note: A-300 Rifle Gunner (X-34 Landspeeder) may have incorrect points due to a typo by AMG (change from 9 to 1, where 10 is far more likely)

### CODE REVIEW

**Comment by Harleqyin** [comment]
Hi guys,
 I really appreciate the work you have done for Legion on BS, and wanted to see if I could do a part to contribute. I am not a programmer, and I have no real idea what I'm doing, but I managed to figure out enough to just change points values, which I hope is of some use. If I've made mistakes with things, I apologize, this is literally my first attempt with Github.
 Cheers.

**Comment by Harleqyin** [comment]
Have finalised all changes as a result of learning more about BS editor. Would like this request approved so I can create new lists in BS. :)

**Comment by PixelTom** [comment]
@JoshWeller looks like you're currently the active maintainer on this repo. Any chance you can help my man @Harleqyin out with his first PR ever?

**Comment by Thairne** [comment]
Since the maintainer isnt responding and your work seems solid, I've added you to the dev team.

**Comment by LuminosityXVII** [comment]
@Harleqyin I made a pull request with some additional changes based on your version; I hope you don't mind. It's a few extra errata to complete the set, some new releases, and a bunch of minor formatting stuff that was not the focus of your efforts.

**Pull request merged**
